import { db } from "@/lib/db";
import { requireAdmin } from "@/lib/auth";
import RoleForm from "@/components/role-form";
import { Pager,param,pageNumber,type AdminSearch } from "@/components/admin-pagination";
export default async function UsersPage({searchParams}:{searchParams:AdminSearch}){
 const viewer=await requireAdmin(),s=await searchParams,q=param(s.q).trim().slice(0,80),role=param(s.role);
 const where={...(q?{displayName:{contains:q,mode:"insensitive" as const}}:{}),...(role==="ADMIN"||role==="LEARNER"?{role}: {})} as import("@/generated/prisma/client").Prisma.ProfileWhereInput;
 const total=await db.profile.count({where}),page=Math.min(pageNumber(s.page),Math.max(1,Math.ceil(total/20)));
 const users=await db.profile.findMany({where,skip:(page-1)*20,take:20,orderBy:[{createdAt:"desc"},{id:"asc"}],select:{id:true,displayName:true,role:true,createdAt:true,_count:{select:{attempts:true,decks:true}}}});
 return <><header className="admin-heading"><div><span className="admin-eyebrow">CỘNG ĐỒNG</span><h1>Tài khoản & phân quyền</h1><p>Hồ sơ người dùng đã xác thực và đăng nhập vào ứng dụng.</p></div></header><form className="admin-filters"><label>Tên hiển thị<input name="q" defaultValue={q} maxLength={80} placeholder="Tìm người dùng…"/></label><label>Vai trò<select name="role" defaultValue={role}><option value="">Tất cả</option><option value="ADMIN">Quản trị viên</option><option value="LEARNER">Người học</option></select></label><button className="button secondary">Lọc</button></form><p className="admin-note">Cấp quyền admin cho phép quản lý mọi nội dung và phân quyền người khác. Bạn không thể tự đổi quyền của mình.</p><div className="admin-table-wrap"><table><thead><tr><th>Người dùng</th><th>Ngày tham gia</th><th>Bộ từ / bài nộp</th><th>Phân quyền</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><strong>{u.displayName}{u.id===viewer.id?" (bạn)":""}</strong><small className="admin-id">{u.id}</small><span className="admin-badge">{u.role==="ADMIN"?"Quản trị viên":"Người học"}</span></td><td>{u.createdAt.toLocaleDateString("vi-VN",{timeZone:"Asia/Ho_Chi_Minh"})}</td><td>{u._count.decks} / {u._count.attempts}</td><td>{u.id===viewer.id?<span>Tài khoản hiện tại</span>:<RoleForm id={u.id} role={u.role}/>}</td></tr>)}</tbody></table>{!users.length&&<p className="admin-empty">Không tìm thấy người dùng.</p>}</div><Pager page={page} total={total} base={`/admin/users?q=${encodeURIComponent(q)}&role=${encodeURIComponent(role)}`}/></>;
}
