"use client";
import Link from "next/link";
import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { Icon } from "./ui";
import { useLearning } from "./learning-provider";
export default function AuthScreen({ register = false }: { register?: boolean }) {
  const { update } = useLearning(); const router = useRouter(); const [message, setMessage] = useState(""); const [showPassword, setShowPassword] = useState(false);
  function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setMessage("Chức năng tài khoản chưa kết nối máy chủ. Bạn có thể chọn Học thử để bắt đầu ngay; mật khẩu không được lưu hoặc gửi đi."); }
  function demo(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const name = String(new FormData(e.currentTarget).get("nickname")).trim(); if (!name) return; update(s => ({ ...s, name })); router.push("/dashboard"); }
  return <main id="main" className="container auth-main"><section className="auth-story"><h1>{register ? "Một khởi đầu nhỏ.\nMột tương lai lớn." : "Rất vui được\ngặp lại bạn."}</h1><p>Hành trình tiếng Anh của riêng bạn,<br />bắt đầu từ những điều thật nhỏ.</p><div className="auth-art"><span>learn.</span><strong>grow.</strong><span>repeat. ✳</span></div><div className="auth-benefits"><span><Icon name="check" size={18} />Flashcard theo chủ đề</span><span><Icon name="check" size={18} />Quiz với giải thích dễ hiểu</span><span><Icon name="check" size={18} />Ghi nhận từng bước tiến</span></div></section><section className="auth-form-panel"><h2>{register ? "Cùng bắt đầu nhé!" : "Chào mừng trở lại!"}</h2><div className="auth-preview-note">Giao diện tài khoản · Chưa kết nối xác thực</div><form className="form-stack" onSubmit={submit}>{register && <label>Tên của bạn<input name="name" autoComplete="name" required placeholder="Bạn muốn T-Rex gọi bạn là gì?" maxLength={40} /></label>}<label>Email<input name="email" type="email" required autoComplete="email" placeholder="ban@example.com" /></label><label>Mật khẩu<span className="password-field"><input name="password" type={showPassword ? "text" : "password"} minLength={8} required autoComplete={register ? "new-password" : "current-password"} placeholder="Ít nhất 8 ký tự" /><button type="button" onClick={() => setShowPassword(!showPassword)} aria-label={showPassword ? "Ẩn mật khẩu" : "Hiện mật khẩu"}>{showPassword ? "Ẩn" : "Hiện"}</button></span></label>{!register && <button type="button" className="text-link forgot-link" onClick={() => setMessage("Khôi phục mật khẩu sẽ khả dụng khi dịch vụ tài khoản được kết nối. Bạn vẫn có thể dùng phần Học thử bên dưới.")}>Quên mật khẩu?</button>}<button className="button primary full">{register ? "Tạo tài khoản" : "Đăng nhập"}<Icon name="arrow" size={18} /></button>{message && <p className="form-message" role="status">{message}</p>}</form><p className="auth-switch">{register ? "Đã có tài khoản?" : "Chưa có tài khoản?"} <Link href={register ? "/login" : "/register"}>{register ? "Đăng nhập" : "Đăng ký"}</Link></p><div className="divider"><span>hoặc khám phá trước</span></div><form className="demo-form" onSubmit={demo}><label>Tên hiển thị khi học thử<input name="nickname" required maxLength={30} placeholder="Tên của bạn" /></label><button className="button secondary full">Học thử ngay<Icon name="arrow" size={18} /></button><small>Không cần tài khoản. Tiến độ được lưu trên trình duyệt.</small></form></section></main>;
}
