"use client";
import Link from "next/link";
import { useState, type FormEvent } from "react";
import { useLearning } from "./learning-provider";
import { DeckArt, EmptyState, Icon } from "./ui";
export default function DeckDetail({ id }: { id: string }) {
  const { decks, ready, state, update } = useLearning(); const deck = decks.find(d => d.id === id); const [query, setQuery] = useState(""); const [adding, setAdding] = useState(false);
  if (!ready) return <main id="main" className="container page-main" role="status">Đang mở bộ từ...</main>;
  if (!deck) return <main id="main" className="container page-main"><EmptyState title="Không tìm thấy bộ từ" description="Bộ từ này chưa có trên trình duyệt của bạn." href="/decks" action="Về thư viện" /></main>;
  const known = state.known[id] || [];
  function addWord(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); const term = String(data.get("term")).trim(); const meaning = String(data.get("meaning")).trim(); if (!term || !meaning) return; update(s => ({ ...s, customDecks: s.customDecks.map(d => d.id === id ? { ...d, words: [...d.words, { id: crypto.randomUUID(), term, meaning, phonetic: String(data.get("phonetic")).trim(), example: String(data.get("example")).trim() }] } : d) })); form.reset(); setAdding(false); }
  const filtered = deck.words.filter(w => `${w.term} ${w.meaning}`.toLowerCase().includes(query.toLowerCase()));
  return <main id="main" className="container page-main"><Link className="back-link" href="/decks"><Icon name="back" size={17} />Thư viện flashcard</Link><section className="deck-detail-hero"><DeckArt deck={deck} large /><div><span className="badge">{deck.level} · {deck.category}</span><h1>{deck.title}</h1><p className="muted">{deck.description}</p><div className="detail-meta"><span><Icon name="cards" size={18} />{deck.words.length} từ vựng</span><span><Icon name="check" size={18} />{known.length} từ đã nhớ</span></div><progress value={known.length} max={Math.max(deck.words.length, 1)} aria-label="Tiến độ bộ từ" /><div className="row wrap">{deck.words.length > 0 && <><Link className="button primary" href={`/decks/${id}/study`}>Học flashcard<Icon name="cards" size={18} /></Link><Link className="button secondary" href={`/quiz/${id}`}>Làm quiz<Icon name="quiz" size={18} /></Link></>}{deck.custom && <button className="button secondary" onClick={() => setAdding(!adding)} aria-expanded={adding}><Icon name="plus" size={18} />Thêm từ mới</button>}</div></div></section>{adding && <form className="panel add-word-form" onSubmit={addWord}><h2>Thêm một từ, mở một cánh cửa.</h2><div className="form-grid"><label>Từ tiếng Anh<input name="term" required maxLength={80} autoFocus placeholder="Ví dụ: inspire" /></label><label>Nghĩa tiếng Việt<input name="meaning" required maxLength={160} placeholder="truyền cảm hứng" /></label><label>Phiên âm (không bắt buộc)<input name="phonetic" maxLength={80} placeholder="/ɪnˈspaɪə/" /></label><label>Câu ví dụ (không bắt buộc)<input name="example" maxLength={250} placeholder="Small steps inspire big changes." /></label></div><div className="row"><button className="button primary">Lưu từ mới</button><button className="button secondary" type="button" onClick={() => setAdding(false)}>Hủy</button></div></form>}<div className="section-heading"><h2>Khám phá từng từ <span className="count-label">{deck.words.length}</span></h2><label className="search-field"><Icon name="search" size={18} /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Tìm từ vựng..." aria-label="Tìm từ vựng" /></label></div>{filtered.length ? <div className="word-list">{filtered.map((word, i) => <div className="word-row" key={word.id}><span className="word-index">{String(i + 1).padStart(2, "0")}</span><div><h3>{word.term}</h3><span className="phonetic">{word.phonetic}</span></div><div><strong>{word.meaning}</strong><p className="muted">{word.example}</p></div><span className={`badge ${known.includes(word.id) ? "mint" : ""}`}>{known.includes(word.id) ? "Đã nhớ" : "Chưa học"}</span></div>)}</div> : <EmptyState title={deck.words.length ? "Chưa tìm thấy từ này" : "Một trang mới đang chờ bạn"} description={deck.words.length ? "Thử một từ tiếng Anh hoặc nghĩa tiếng Việt khác." : "Chọn Thêm từ mới để bắt đầu xây dựng bộ từ của riêng mình."} />}</main>;
}
