"use client";
import Link from "next/link";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { makeQuiz, tests, type Question } from "@/lib/learning-data";
import { useLearning } from "./learning-provider";
import { EmptyState, Icon } from "./ui";
export default function QuestionSession({ id, quiz = false }: { id: string; quiz?: boolean }) {
  const { decks, ready } = useLearning(); const deck = decks.find(d => d.id === id); const test = tests.find(t => t.id === id);
  if (!ready) return <main id="main" className="container page-main" role="status">Đang chuẩn bị câu hỏi...</main>;
  if (quiz ? !deck?.words.length : !test) return <main id="main" className="container page-main"><EmptyState title="Chưa tìm thấy bài luyện tập" description="Chọn một bài khác để tiếp tục hành trình nhé." href={quiz ? "/quiz" : "/tests"} action="Chọn bài luyện tập" /></main>;
  return <QuestionPlayer key={id} title={quiz ? `Quiz: ${deck!.title}` : test!.title} questions={quiz ? makeQuiz(deck!) : test!.questions} quiz={quiz} />;
}
function QuestionPlayer({ title, questions, quiz }: { title: string; questions: Question[]; quiz: boolean }) {
  const { addAttempt } = useLearning(); const router = useRouter(); const [index, setIndex] = useState(0); const [answers, setAnswers] = useState<number[]>([]); const [checked, setChecked] = useState(false); const [submitting, setSubmitting] = useState(false);
  const question = questions[index]; const selected = answers[index];
  function next() { if (index < questions.length - 1) { setIndex(i => i + 1); setChecked(false); } else { if (submitting) return; setSubmitting(true); const id = crypto.randomUUID(); addAttempt({ id, title, date: new Date().toISOString(), questions, answers, score: answers.filter((a, i) => a === questions[i].answer).length }); router.push(`/attempts/${id}`); } }
  return <main id="main" className="container page-main question-main"><div className="study-top"><Link className="back-link" href={quiz ? "/quiz" : "/tests"}><Icon name="back" size={18} />{quiz ? "Quiz từ vựng" : "Online Test"}</Link><span className="badge">{title}</span><span>Câu {index + 1} / {questions.length}</span></div><progress value={index + (checked ? 1 : 0)} max={questions.length} aria-label="Tiến độ làm bài" /><div className="question-layout"><section className="panel question-panel"><p className="eyebrow">{quiz ? "LET’S SEE WHAT YOU REMEMBER" : "TAKE A BREATH. YOU’VE GOT THIS."}</p><h1>{question.prompt}</h1><p className="muted">Chọn một đáp án đúng bên dưới.</p><div className="answer-options" role="group" aria-label="Các đáp án">{question.options.map((option, i) => <button key={i} disabled={checked} aria-pressed={selected === i} className={`answer-option ${selected === i ? "chosen" : ""} ${checked && i === question.answer ? "correct" : ""} ${checked && selected === i && i !== question.answer ? "incorrect" : ""}`} onClick={() => setAnswers(a => { const next = [...a]; next[index] = i; return next; })}><span>{String.fromCharCode(65 + i)}</span>{option}{checked && i === question.answer && <Icon name="check" size={19} />}</button>)}</div>{checked && <div className={`answer-explanation ${selected === question.answer ? "correct" : "incorrect"}`} role="status"><strong>{selected === question.answer ? "Chính xác! Thêm một bước tiến." : "Chưa đúng, nhưng bạn vừa học thêm rồi."}</strong><p>{question.explanation}</p></div>}<div className="question-bottom"><span className="muted">{index + 1} / {questions.length} câu hỏi</span>{checked ? <button className="button primary" disabled={submitting} onClick={next}>{index === questions.length - 1 ? "Xem kết quả" : "Câu tiếp theo"}<Icon name="arrow" size={17} /></button> : <button className="button primary" disabled={selected === undefined} onClick={() => setChecked(true)}>Kiểm tra đáp án<Icon name="check" size={17} /></button>}</div></section><aside className="question-aside"><span className="word-spark">✳</span><h3>Tiến bộ từ từng câu hỏi.</h3><p className="muted">Không sao nếu bạn chưa biết. Mỗi câu trả lời đều là một cơ hội để nhớ lâu hơn.</p><div className="question-dots">{questions.map((_, i) => <span className={i < index ? "done" : i === index ? "current" : ""} key={i}>{i < index ? <Icon name="check" size={15} /> : i + 1}</span>)}</div><small>Kết quả được lưu trên trình duyệt này.</small></aside></div></main>;
}
