"use client";
import Link from "next/link";
import PronunciationButton from "./pronunciation-button";
import { useEffect, useState } from "react";
import { useLearning } from "./learning-provider";
import { EmptyState, Icon } from "./ui";
export default function StudySession({ id }: { id: string }) {
  const { decks, ready, markWord } = useLearning(); const deck = decks.find(d => d.id === id);
  const [index, setIndex] = useState(0); const [flipped, setFlipped] = useState(false); const [remembered, setRemembered] = useState(0);
  const word = deck?.words[index]; const complete = !!deck && index >= deck.words.length;
  useEffect(() => { function key(event: KeyboardEvent) { if (event.code === "Space" && event.target === document.body) { event.preventDefault(); setFlipped(f => !f); } } window.addEventListener("keydown", key); return () => { window.removeEventListener("keydown", key); window.speechSynthesis?.cancel(); }; }, []);
  if (!ready) return <main id="main" className="container page-main" role="status">Đang chuẩn bị thẻ học...</main>;
  if (!deck || !deck.words.length) return <main id="main" className="container page-main"><EmptyState title="Chưa có thẻ để học" description="Hãy chọn bộ từ khác hoặc thêm từ vào bộ của bạn." href="/decks" action="Về thư viện" /></main>;
  function next(known: boolean) { if (!word) return; markWord(id, word.id, known); if (known) setRemembered(n => n + 1); setIndex(i => i + 1); setFlipped(false); window.speechSynthesis?.cancel(); }
  return <main id="main" className="container page-main study-main"><div className="study-top"><Link className="back-link" href={`/decks/${id}`}><Icon name="back" size={18} />{deck.title}</Link><span className="badge">FLASHCARD · {deck.level}</span><span>{Math.min(index + 1, deck.words.length)} / {deck.words.length} thẻ</span></div><progress value={index} max={deck.words.length} aria-label="Tiến độ phiên học" />{complete ? <div className="session-complete"><span className="completion-symbol">✳</span><p className="eyebrow">ONE SMALL STEP FORWARD</p><h1>Giỏi lắm, bạn đã hoàn thành!</h1><p className="muted">Bạn đã học {deck.words.length} từ và tự đánh giá nhớ {remembered} từ trong phiên này.</p><div className="row center wrap"><Link className="button primary" href={`/quiz/${id}`}>Kiểm tra với quiz<Icon name="quiz" size={18} /></Link><button className="button secondary" onClick={() => { setIndex(0); setRemembered(0); }}>Học lại bộ từ</button></div><Link className="text-link" href="/dashboard">Xem tiến độ của tôi<Icon name="arrow" size={18} /></Link></div> : word && <><div className="study-title"><p className="eyebrow">TAKE YOUR TIME. MAKE IT STICK.</p><h1>Một thẻ nhỏ, thêm một điều mới.</h1><p className="muted">Đọc từ, đoán nghĩa rồi lật thẻ để khám phá.</p></div><div className="study-card-wrap"><button className={`study-card ${flipped ? "is-flipped" : ""}`} onClick={() => setFlipped(!flipped)} aria-label={flipped ? "Lật về mặt tiếng Anh" : "Lật thẻ để xem nghĩa"}><span className="study-card-label">{flipped ? "NGHĨA TIẾNG VIỆT" : "ENGLISH WORD"}<Icon name="cards" size={20} /></span><span className="study-card-content"><strong>{flipped ? word.meaning : word.term}</strong><span className="phonetic">{flipped ? word.term : word.phonetic}</span>{flipped && <span className="study-example">“{word.example || "Hãy thử đặt một câu với từ mới này."}”</span>}</span><span className="study-flip-hint"><Icon name="shuffle" size={16} />Nhấn để lật thẻ</span></button><PronunciationButton key={word.id} term={word.term} className="study-pronunciation"/></div><div className="study-controls">{flipped ? <><button className="button secondary" onClick={() => next(false)}><Icon name="close" size={19} />Cần ôn lại</button><button className="button primary" onClick={() => next(true)}><Icon name="check" size={19} />Đã nhớ từ này</button></> : <button className="button primary" onClick={() => setFlipped(true)}>Khám phá nghĩa<Icon name="shuffle" size={18} /></button>}</div><p className="keyboard-hint"><kbd>Space</kbd> để lật thẻ · Một chút đều đặn, một bước tiến xa.</p></>}</main>;
}
