const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const tables=['profiles','decks','words','saved_decks','word_progress','daily_word_activity','tests','test_questions','learning_sessions','attempts'];
async function backup(mode,{same=false,occupied=false}={}){const queries=[],output=[],snapshot={format:1,tables:Object.fromEntries(tables.map(t=>[t,[]]))};const mockProcess={argv:['node','backup',mode,'backup.json'],env:{DIRECT_URL:'postgresql://u:p@source/db',RESTORE_DATABASE_URL:same?'postgresql://u:p@source/db':'postgresql://u:p@staging/other'},exitCode:0};const promise=vm.runInNewContext(fs.readFileSync('scripts/backup.cjs','utf8'),{require:n=>n==='dotenv/config'?{}:n==='node:fs'?{readFileSync:()=>JSON.stringify(snapshot),mkdirSync:()=>{},writeFileSync:(_p,_s,o)=>{assert.equal(o.flag,'wx');}}:n==='pg'?{Client:class{async connect(){}async end(){}async query(sql){queries.push(sql);if(sql.startsWith('SELECT 1'))return {rowCount:occupied?1:0,rows:[]};if(sql.includes('column_name'))return {rows:[]};if(sql.includes('count(*)'))return {rows:[{n:0}]};return {rows:[]};}}}:require(n),process:mockProcess,URL,Date,console:{log:m=>output.push(m),error:m=>output.push(m)}});await promise;return {queries,output,code:mockProcess.exitCode};}
test('backup export opens a consistent read-only transaction',async()=>{const r=await backup('export');assert.equal(r.code,0);assert(r.queries.includes('BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY'));assert.equal(r.queries.at(-1),'COMMIT');});
test('restore rehearsal always rolls back on success',async()=>{const r=await backup('restore-check');assert.equal(r.code,0);assert.equal(r.queries.at(-1),'ROLLBACK');assert(!r.queries.includes('COMMIT'));});
test('restore refuses a populated destination',async()=>{const r=await backup('restore',{occupied:true});assert.equal(r.code,1);assert.equal(r.queries.at(-1),'ROLLBACK');assert(!r.queries.some(q=>q.startsWith('INSERT')));});
test('restore rejects source database before connecting',async()=>{const r=await backup('restore',{same:true});assert.equal(r.code,1);assert.equal(r.queries.length,0);});
async function finalize({fail=false,quiz=false}={}){const queries=[],inserts=[];const state={quiz,questions:[{prompt:'Q',options:['a','b'],answer:0,explanation:'A'}],answers:[-1],index:0,phase:'answering',deadline:Date.now()-20000,now:Date.now()-25000,endedAt:0,revision:0};const processMock={env:{},exitCode:0};await vm.runInNewContext(fs.readFileSync('scripts/finalize-sessions.cjs','utf8'),{require:n=>n==='dotenv/config'?{}:n==='pg'?{Client:class{async connect(){}async end(){}async query(sql,args){queries.push(sql);if(sql.startsWith('SELECT id FROM learning_sessions'))return {rows:[{id:'session'}],rowCount:1};if(sql.startsWith('SELECT * FROM learning_sessions'))return {rows:[{id:'session',user_id:'owner',kind:quiz?'QUIZ':'TEST',source_id:'source',title:'Exam',state}]};if(sql.includes('INSERT INTO attempts')){if(fail)throw Error('database');inserts.push(args);}return {rows:[]};}}}:require(n),process:processMock,Date,console:{log:()=>{},error:()=>{}}});return {queries,inserts,code:processMock.exitCode,state};}
test('finalizer catches up expired quiz and records original deadline with unanswered score zero',async()=>{const r=await finalize({quiz:true});assert.equal(r.code,0);assert.equal(r.inserts.length,1);assert.equal(r.inserts[0][8],0);assert.equal(r.inserts[0][9].getTime(),r.state.deadline+1500);assert(r.queries.some(q=>q.includes('ON CONFLICT(id) DO NOTHING')));assert.equal(r.queries.at(-1),'COMMIT');});
test('finalizer rolls back the session transition if result saving fails',async()=>{const r=await finalize({fail:true});assert.equal(r.code,1);assert.equal(r.queries.at(-1),'ROLLBACK');assert(!r.queries.includes('COMMIT'));});
function cron({secret='s'.repeat(32),fail=false}={}){const ts=require('typescript');function compile(file,resolve){const mod={exports:{}};new Function('exports','module','require',ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText)(mod.exports,mod,resolve);return mod.exports;}const engine=compile('src/lib/session-engine.ts',n=>n==='@/lib/reading'?compile('src/lib/reading.ts',require):require(n)),state=engine.begin([{prompt:'Q',options:['a','b'],answer:0,explanation:'A'}],false,100,Date.now()-10000);let calls=0,saved;const db={$queryRaw:async()=>{calls++;return [{id:'session'}];},$transaction:async fn=>fn({$queryRaw:async()=>[{locked:true}],learningSession:{findUnique:async()=>({id:'session',userId:'user',kind:'TEST',sourceId:'source',title:'T',state}),update:async()=>{}},test:{findUnique:async()=>null},attempt:{upsert:async data=>{if(fail)throw Error();saved=data;}}})};const code=ts.transpileModule(fs.readFileSync('src/app/api/cron/finalize-sessions/route.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText;const mod={exports:{}};vm.runInNewContext(code,{exports:mod.exports,module:mod,require:n=>n==='@/lib/db'?{db}:n==='@/lib/session-engine'?engine:require(n),process:{env:{CRON_SECRET:secret}},Response,Buffer,Date,console:{info:()=>{}}});return {GET:mod.exports.GET,calls:()=>calls,saved:()=>saved};}
test('Vercel cron rejects missing configuration and unauthorized requests before querying DB',async()=>{const a=cron({secret:''});assert.equal((await a.GET(new Request('http://local'))).status,503);assert.equal(a.calls(),0);const b=cron();assert.equal((await b.GET(new Request('http://local',{headers:{authorization:'Bearer wrong'}}))).status,401);assert.equal(b.calls(),0);});
test('authorized Vercel cron retains result even when the source was deleted',async()=>{const h=cron();const response=await h.GET(new Request('http://local',{headers:{authorization:'Bearer '+'s'.repeat(32)}}));assert.equal(response.status,200);assert.equal((await response.json()).finished,1);assert.equal(h.saved().create.testId,null);assert.equal(h.saved().create.score,0);assert.equal(Object.keys(h.saved().update).length,0);});
test('cron returns a failure status if a transaction cannot save its result',async()=>{const h=cron({fail:true});assert.equal((await h.GET(new Request('http://local',{headers:{authorization:'Bearer '+'s'.repeat(32)}}))).status,500);});
