import Link from "next/link";
import { db } from "@/lib/db";
import { requireAdmin } from "@/lib/auth";
import { Pager,param,pageNumber,type AdminSearch } from "@/components/admin-pagination";
export default async function ContentPage({searchParams}:{searchParams:AdminSearch}){
 await requireAdmin();const s=await searchParams,kind=param(s.kind)==="test"?"test":"deck",q=param(s.q).trim().slice(0,160),status=param(s.status),requested=pageNumber(s.page);
 const common={...(q?{OR:[{title:{contains:q,mode:"insensitive" as const}},{category:{contains:q,mode:"insensitive" as const}}]}:{})};
 const deckWhere={...common,...(status==="public"?{visibility:"PUBLIC" as const}:status==="draft"?{visibility:"PRIVATE" as const}:{})};
 const testWhere={...common,...(status==="public"?{published:true}:status==="draft"?{published:false}:{})};
 const total=kind==="deck"?await db.deck.count({where:deckWhere}):await db.test.count({where:testWhere});
 const page=Math.min(requested,Math.max(1,Math.ceil(total/20))),paging={skip:(page-1)*20,take:20,orderBy:[{updatedAt:"desc" as const},{id:"asc" as const}]};
 const rows=kind==="deck"?(await db.deck.findMany({where:deckWhere,...paging,include:{_count:{select:{words:true}},owner:{select:{displayName:true}}}})).map(d=>({id:d.id,title:d.title,category:d.category,level:d.level,published:d.visibility==="PUBLIC",count:d._count.words,owner:d.owner?.displayName??"Hệ thống",updatedAt:d.updatedAt})):(await db.test.findMany({where:testWhere,...paging,include:{_count:{select:{questions:true}}}})).map(t=>({...t,count:t._count.questions,owner:`${t.minutes} phút` }));
 const base=`/admin/content?kind=${kind}&q=${encodeURIComponent(q)}&status=${encodeURIComponent(status)}`;
 return <><header className="admin-heading"><div><span className="admin-eyebrow">NỘI DUNG HỌC TẬP</span><h1>{kind==="deck"?"Bộ từ vựng":"Đề kiểm tra"}</h1><p>Soạn, chỉnh sửa và quản lý trạng thái nội dung.</p></div><Link className="button primary" href={`/admin/${kind==="deck"?"decks":"tests"}/new`}>+ {kind==="deck"?"Tạo bộ từ":"Tạo đề"}</Link></header>{(s.saved==="1"||s.deleted==="1")&&<p className="admin-success" role="status">{s.saved==="1"?"Đã lưu nội dung vào database.":"Đã xóa nội dung."}</p>}<form className="admin-filters"><input type="hidden" name="kind" value={kind}/><label>Tìm kiếm<input name="q" defaultValue={q} maxLength={160} placeholder="Tên hoặc chủ đề…"/></label><label>Trạng thái<select name="status" defaultValue={status}><option value="">Tất cả</option><option value="public">Công khai</option><option value="draft">Bản nháp / riêng tư</option></select></label><button className="button secondary">Lọc</button><Link href={`/admin/content?kind=${kind}`}>Đặt lại</Link></form><div className="admin-table-wrap"><table><thead><tr><th>Nội dung</th><th>Trình độ</th><th>Số {kind==="deck"?"từ":"câu"}</th><th>{kind==="deck"?"Chủ sở hữu":"Thời gian"}</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><strong>{row.title}</strong><small>{row.category}</small></td><td>{row.level}</td><td>{row.count}</td><td>{row.owner}</td><td><span className={`admin-badge ${row.published?"published":""}`}>{row.published?"Công khai":"Bản nháp / riêng tư"}</span></td><td><Link className="admin-edit" href={`/admin/${kind==="deck"?"decks":"tests"}/${encodeURIComponent(row.id)}`}>Chỉnh sửa →</Link></td></tr>)}</tbody></table>{!rows.length&&<div className="admin-empty">Không có nội dung phù hợp. Thử đổi bộ lọc hoặc tạo nội dung mới.</div>}</div><Pager page={page} total={total} base={base}/></>;
}
